# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparray.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsparray.proto\x12\x07sparray\x1a\x1cgoogle/protobuf/struct.proto\"A\n\x11\x44\x65nseNdArrayProto\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\r\x12\r\n\x05\x64type\x18\x03 \x01(\t\"A\n\x08\x44ocProto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x62lob\x18\x02 \x01(\x0c\x12\x0c\n\x04text\x18\x03 \x01(\t\x12\r\n\x05\x64type\x18\x04 \x01(\t\"0\n\rDocArrayProto\x12\x1f\n\x04\x64ocs\x18\x01 \x03(\x0b\x32\x11.sparray.DocProtob\x06proto3')



_DENSENDARRAYPROTO = DESCRIPTOR.message_types_by_name['DenseNdArrayProto']
_DOCPROTO = DESCRIPTOR.message_types_by_name['DocProto']
_DOCARRAYPROTO = DESCRIPTOR.message_types_by_name['DocArrayProto']
DenseNdArrayProto = _reflection.GeneratedProtocolMessageType('DenseNdArrayProto', (_message.Message,), {
  'DESCRIPTOR' : _DENSENDARRAYPROTO,
  '__module__' : 'sparray_pb2'
  # @@protoc_insertion_point(class_scope:sparray.DenseNdArrayProto)
  })
_sym_db.RegisterMessage(DenseNdArrayProto)

DocProto = _reflection.GeneratedProtocolMessageType('DocProto', (_message.Message,), {
  'DESCRIPTOR' : _DOCPROTO,
  '__module__' : 'sparray_pb2'
  # @@protoc_insertion_point(class_scope:sparray.DocProto)
  })
_sym_db.RegisterMessage(DocProto)

DocArrayProto = _reflection.GeneratedProtocolMessageType('DocArrayProto', (_message.Message,), {
  'DESCRIPTOR' : _DOCARRAYPROTO,
  '__module__' : 'sparray_pb2'
  # @@protoc_insertion_point(class_scope:sparray.DocArrayProto)
  })
_sym_db.RegisterMessage(DocArrayProto)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DENSENDARRAYPROTO._serialized_start=56
  _DENSENDARRAYPROTO._serialized_end=121
  _DOCPROTO._serialized_start=123
  _DOCPROTO._serialized_end=188
  _DOCARRAYPROTO._serialized_start=190
  _DOCARRAYPROTO._serialized_end=238
# @@protoc_insertion_point(module_scope)
